### ISSUE TITLE
Closing Jenkins administration information gaps ...

### ISSUE THREAD

**Issue by HannesSommer** [ethz-asl/continuous_integration#56]
Do we ( @dymczykm ,  @schneith, and me ) have all necessary information?

I'm missing, probably :
* where are the macs (physically)?
* who is renting (formally) and how the virtual servers?
* are there any backup systems configured (workers:  ubuntu, mac os x; Jenkins project configurations)

**Comment by simonlynen** [comment]
> where are the macs (physically)?

The mac is in our office next to Marcin's desk.

> who is renting (formally) and how the virtual servers?

Stefan Bertschi, paid by Google Tango funds (formerly paid by V-Charge).

> are there any backup systems configured (workers: ubuntu, mac os x; Jenkins project configurations)

Workers don't need a config backup since the config is done automatically via webstart. Thomas set up a worker so he should know how to config ROS etc.
Jenkins master config is backup'ed daily into the home dir of the jenkins user. The full virtual-machine is backup'ed via ETH backup system.

**Comment by HannesSommer** [comment]
Thanks.
One last question : was there a reason (different from too much effort) not to have Jenkins notification emails set up? (E.g. in case of failure of an automatic build to the commit author)

**Comment by simonlynen** [comment]
oh, we can do that if people don't care about the additional email traffic.

**Comment by HannesSommer** [comment]
The content is transfered to the asl wiki, where it belongs.
